controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
hub:
    path: /myHub
    controller: App\Controller\HubController::index