# config/routes.yaml
voc_main2:
    path: /Vokabeltrainer
    controller: App\Controller\MainController::test
voc_main:
    path: /
    controller: App\Controller\MainController::test
compare_vocs:
    path: /compare_answer
    controller: App\Controller\MainController::compareVocabs
api:
    path: /api
    controller: App\Controller\MainController::appAPI
dashboard:
    path: /admin
    controller: App\Controller\Admin\backendController::index
login:
    path: /login
    controller: App\Controller\LoginController::index
app_logout:
    path: /logout
    methods: GET #??
test_register:
    path: /registration
    controller: App\Controller\RegistrationController::register
