controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
index:
   path: /website/
   controller: App\Controller\HomeController::index
